[package]
name = "regex-tester"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[dependencies]
console_error_panic_hook = "0.1"
leptos = { version = "0.7", features = ["csr"] }
reactive_stores = "0.1"
regex = "1.11"
regex-syntax = "0.8"
tailwind_fuse = { version = "0.3", features = ["variant"] }
# wasm-bindgen = "0.2"
